/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.kedaikopigui.layout;

/**
 *
 * @author hp
 */
public class BorderLayoutMenu extends javax.swing.JFrame {

    /**
     * Creates new form BorderLayoutMenu
     */
    public BorderLayoutMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        lblnamaKopi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdeskripsi = new javax.swing.JTextArea();
        lblHarga = new javax.swing.JLabel();
        lblJamBuka = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout(6, 6));

        lblJudul.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJudul.setText("Kopi Best seller");
        jPanel1.add(lblJudul, java.awt.BorderLayout.PAGE_START);

        lblnamaKopi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblnamaKopi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblnamaKopi.setText("Capuccino");
        lblnamaKopi.setPreferredSize(new java.awt.Dimension(110, 20));
        jPanel1.add(lblnamaKopi, java.awt.BorderLayout.LINE_START);

        txtdeskripsi.setEditable(false);
        txtdeskripsi.setColumns(20);
        txtdeskripsi.setLineWrap(true);
        txtdeskripsi.setRows(5);
        txtdeskripsi.setText("Kopi murah untuk semua kalangan");
        txtdeskripsi.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtdeskripsi);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        lblHarga.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHarga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHarga.setText("Rp.20.000");
        lblHarga.setPreferredSize(new java.awt.Dimension(110, 20));
        jPanel1.add(lblHarga, java.awt.BorderLayout.LINE_END);

        lblJamBuka.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJamBuka.setText("Buka Setiap Minggu 07.00 - 15.00");
        jPanel1.add(lblJamBuka, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BorderLayoutMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BorderLayoutMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BorderLayoutMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BorderLayoutMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BorderLayoutMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblJamBuka;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblnamaKopi;
    private javax.swing.JTextArea txtdeskripsi;
    // End of variables declaration//GEN-END:variables
}
