/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.kedaikopigui.layout;

/**
 *
 * @author hp
 */
public class CardLoyoutPesan extends javax.swing.JFrame {

    /**
     * Creates new form CardLoyoutPesan
     */
    public CardLoyoutPesan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPilih = new javax.swing.JPanel();
        lblLangakh1 = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        txtKopi = new javax.swing.JTextField();
        btnLanjut = new javax.swing.JButton();
        panelKonfirmasi = new javax.swing.JPanel();
        lblLangkah2 = new javax.swing.JLabel();
        lblPesanan = new javax.swing.JLabel();
        btnSelesai = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        lblLangakh1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblLangakh1.setText("Langkah 1 dari 2 - Pilih Kopi");

        lblNama.setText("Nama Kopi:");

        txtKopi.setText("Latte");

        btnLanjut.setText("Lanjut");
        btnLanjut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanjutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPilihLayout = new javax.swing.GroupLayout(PanelPilih);
        PanelPilih.setLayout(PanelPilihLayout);
        PanelPilihLayout.setHorizontalGroup(
            PanelPilihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPilihLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPilihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLangakh1)
                    .addGroup(PanelPilihLayout.createSequentialGroup()
                        .addComponent(lblNama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKopi, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(179, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPilihLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLanjut)
                .addContainerGap())
        );
        PanelPilihLayout.setVerticalGroup(
            PanelPilihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPilihLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLangakh1)
                .addGap(18, 18, 18)
                .addGroup(PanelPilihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNama)
                    .addComponent(txtKopi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                .addComponent(btnLanjut)
                .addContainerGap())
        );

        getContentPane().add(PanelPilih, "pilih");

        lblLangkah2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblLangkah2.setText("Langkah 2 dari 2 - Konfirmasi");

        lblPesanan.setText("Kopi yang dipilih: -");

        btnSelesai.setText("Selesai");
        btnSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelesaiActionPerformed(evt);
            }
        });

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelKonfirmasiLayout = new javax.swing.GroupLayout(panelKonfirmasi);
        panelKonfirmasi.setLayout(panelKonfirmasiLayout);
        panelKonfirmasiLayout.setHorizontalGroup(
            panelKonfirmasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKonfirmasiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelKonfirmasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLangkah2)
                    .addComponent(lblPesanan))
                .addContainerGap(169, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelKonfirmasiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKembali)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSelesai)
                .addContainerGap())
        );
        panelKonfirmasiLayout.setVerticalGroup(
            panelKonfirmasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKonfirmasiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLangkah2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPesanan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE)
                .addGroup(panelKonfirmasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelesai)
                    .addComponent(btnKembali))
                .addContainerGap())
        );

        getContentPane().add(panelKonfirmasi, "konfirmasi");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLanjutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanjutActionPerformed
        // TODO add your handling code here:
        lblPesanan.setText("Kopi yang dipilih: " + txtKopi.getText());
        java.awt.CardLayout cl = (java.awt.CardLayout) getContentPane().getLayout();
        cl.show(getContentPane(), "konfirmasi");
    }//GEN-LAST:event_btnLanjutActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        java.awt.CardLayout cl = (java.awt.CardLayout) getContentPane().getLayout();
        cl.show(getContentPane(), "Pilih");
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelesaiActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(this, "Pesan disimpan");
    }//GEN-LAST:event_btnSelesaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CardLoyoutPesan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CardLoyoutPesan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CardLoyoutPesan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CardLoyoutPesan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CardLoyoutPesan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPilih;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnLanjut;
    private javax.swing.JButton btnSelesai;
    private javax.swing.JLabel lblLangakh1;
    private javax.swing.JLabel lblLangkah2;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblPesanan;
    private javax.swing.JPanel panelKonfirmasi;
    private javax.swing.JTextField txtKopi;
    // End of variables declaration//GEN-END:variables
}
